Neos:
  Flow:
    mvc:
      routes:
        'Flownative.Pixxio':
          position: 'after Neos.Neos'

  Media:
    assetSources:
      'flownative-pixxio':
        assetSource: 'Flownative\Pixxio\AssetSource\PixxioAssetSource'
        assetSourceOptions:

          # The customer-specific endpoint URI pointing to the Pixx.io API:
          # Example: 'https://flownative.pixxio.media/cgi-bin/api/pixxio-api.pl'
          apiEndpointUri: ''

          # The API key of this Pixx.io integration.
          # Please get in touch with Pixx.io support in order to get this key.
          apiKey: ''

          # Options for the Guzzle HTTP Client as specified here
          # see http://docs.guzzlephp.org/en/6.5/request-options.html
          # Use this to configure custom certificates or to disable cert verification
          apiClientOptions: {}

          # A pixx.io user refresh token which is shared across all editors in
          # this Neos installation.
          # sharedRefreshToken: ''

          # Additional configuration for specific media types
          mediaTypes:
            'image/svg+xml':
              usePixxioThumbnailAsOriginal: true
            'application/pdf':
              usePixxioThumbnailAsOriginal: true

          # This plugin can automatically tag files in the pixxio media library
          # when they are in use, and remove the tag once they are not used anymore
          autoTagging:
            enable: false
            inUseTag: 'used-by-neos'

  Neos:
    modules:
      management:
        submodules:
          flownativePixxio:
            controller: \Flownative\Pixxio\Controller\PixxioController
            label: 'pixx.io'
            description: 'Flownative.Pixxio:Main:moduleDescription'
            icon: 'icon-photo'
            privilegeTarget: 'Flownative.Pixxio:ManageConnection'
